---
- name: copy
  hosts: testservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "copy file"
      copy: src=/home/ubuntu/index.html dest=/var/www/html/index.html
~                                                                               
~                                                                               
~                  
