---
- name: install apache & php & mysql
  hosts: testservers
  become: true
  become_user: root
  gather_facts: true
  tasks:
     - name: "Install apache2"
       package: name=apache2 state=present
     - name: "Install apache2-php5"
       package: name=apache2 state=present
     - name: "Install php-cli"
       package: name=php-cli state=present
     - name: "Install php-mcrypt"
       package: name=php-mcrypt state=present
     - name: "Install php-gd"
       package: name=php-gd state=present
     - name: "Install php-mysql"
       package: name=php-mysql state=present
     - name: "Install php-mysqlserver"
       package: name=php-mysql-server state=present
       
     
     - name: "Install python3-pymysq"
       package: name=python3-pymysq state=present
     - name: "Install libapache2-mod-php"
       package: name=libapache2-mod-php state=present
     - name: "Install php_modules"
       package: name=php-php_modules state=present
     
